---
- name: Install elasticsearch repo key
  shell: "wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -"
  sudo: yes
- name: Add repo
  shell: echo "deb https://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
  #apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.2/debian stable main' state=present
  sudo: yes
- name: Install elasticsearch packages
  action: apt name="{{ item }}" state=latest update_cache=true
  sudo: yes
  with_items:
    - elasticsearch
- name: Start the elasticsearch service
  action: service name=elasticsearch state=started
  sudo: yes
